name : Postman Collection Workflow

on:
  push: 
    branches: [main]
  workflow_dispatch:
  schedule: 
    - cron: 00 12 * * * #8am GST Everyday
    - cron: 30 23 * * * #7:30pm GST Everyday
    - cron: 30 15 * * 1-5 #11:30pm GST from Monday to Friday

jobs: 
  run-postman-tests:
    runs-on: ec2-github-runner
    steps: 
      - name: Checkout the code
        uses: actions/checkout@v6.0.1

      - name: Install Nodejs and npm
        uses: actions/setup-node@v6.1.0
        with:
          node-version: '22'

      - name: Install Newman and Html-extra globally
        run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection with Newman
        run: |
             newman run 'Inwarranty-flow Collection.postman_collection.json' \
             -e QA.postman_environment.json \
             -r cli,htmlextra \
             --reporter-htmlextra-export ./newman/index.html

      - name: Newman Report
        if: always()
        uses: actions/upload-artifact@v6.0.0
        with:
         name: Newman Report
         path: newman/*.html

      - name: Creating Github page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v7
        with: 
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Phoenix Inwarranty Flow Test Execution Notification
          to: vickybenjamin20@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
                Hi,
                Phoenix Inwarranty flow test has been executed. The report has been published and the URL 
                is: https://vickybenjamin.github.io/Phoenix-Inwarranty-Flow/
                




















      
    
